apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::455686116917:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-8BQD8VWYG8FC
      username: system:node:{{EC2PrivateDNSName}}
      - system:masters
      rolearn: arn:aws:iam::455686116917:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2022-10-04T23:54:01Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1680"
  uid: 7cb353b8-a8e5-403b-92f4-8e2ab71ba5fb
