apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::565605263567:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-1BGF3HGLBH4QQ
      username: system:node:{{EC2PrivateDNSName}}
kind: ConfigMap
metadata:
  creationTimestamp: "2022-10-01T01:29:47Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1543"
  uid: eae6ba7c-897f-4454-95d8-5d8de92beb5d
