apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::455686116917:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-DWAIMN8EV3Z6
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
        rolearn: arn:aws:iam::<ACCOUNT_ID>:role/UdacityFlaskDeployCBKubectlRole
        username: build   
kind: ConfigMap
metadata:
  creationTimestamp: "2022-10-08T21:22:25Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1679"
  uid: 31b139b6-ec64-4535-80b2-d9df6587071e
