apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::565605263567:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-4SZY747NRTIU
      username: system:node:{{EC2PrivateDNSName}}
      - system:masters
      rolearn: arn:aws:iam::565605263567:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2022-10-02T11:23:11Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1866"
  uid: 18c39253-74b4-4aae-8ae7-aad151834437
